export const mockedInteractionData = (
  contactDirection: "INBOUND",
  ani?: string,
  dnis?: string
) => {
  return {
    mediaType: "telephony",
    // mediaType: "chat",
    mediaChannel: "broadcloud",
    queueId: "AXj7J67QX-tU5CjVIxNA",
    ani,
    orgId: "12700722-cd25-46b9-971e-ed0ce9f140c6",
    isFcManaged: true,
    owner: "7520516a-3583-42c0-9ebc-186feb9e07cc",
    interactionId: "897433e1-82f4-4c65-95e4-b1aeb92778ec",
    mediaResourceId: "897433e1-82f4-4c65-95e4-b1aeb92778ec",
    state: "connected",
    destAgentId: "",
    consultHold: false,
    consultMediaResourceId: "",
    isTerminated: false,
    agentId: "7520516a-3583-42c0-9ebc-186feb9e07cc",
    ownerName: "Agent1 Demo",
    ownerPhoneNumber: "12263762555",
    isWrapUp: false,
    hasJoined: true,
    isOffered: true,
    dnis: "+15165179312",
    phoneNumber: "+18505598991",
    virtualTeamName: "bmclella_voice_Q",
    ronaTimeout: "22",
    isConferencing: false,
    isRecordingPaused: false,
    isRecorded: false,
    isPauseResumeEnabled: false,
    contactDirection,
    outboundType: null,
    isHold: false,
    ctqInProgress: false,
    outdialTransferToQueueEnabled: false,
    timeStamp: 1682712932773,
    consultTimeStamp: 1682712932773,
    wrapUpTimestamp: null,
    holdTimestamp: null,
    consultHoldTimestamp: null,
    callAssociatedData: {
      //   JDSDefaultFilter: {
      //     agentEditable: true,
      //     agentViewable: true,
      //     displayName: "JDSDefaultFilter",
      //     global: false,
      //     isSecure: false,
      //     name: "JDSDefaultFilter",
      //     reportable: false,
      //     secureKeyId: "",
      //     secureKeyVersion: 0,
      //     type: "STRING",
      //     value: "Mortgage",
      //   },
      //   JDSDivision: {
      //     agentEditable: true,
      //     agentViewable: true,
      //     displayName: "JDSDivision",
      //     global: false,
      //     isSecure: false,
      //     name: "JDSDivision",
      //     reportable: false,
      //     secureKeyId: "",
      //     secureKeyVersion: 0,
      //     type: "STRING",
      //     value: "walmart",
      //   },
      Address: {
        agentEditable: true,
        agentViewable: true,
        displayName: "Address",
        global: false,
        isSecure: false,
        name: "Address",
        reportable: false,
        secureKeyId: "",
        secureKeyVersion: 0,
        type: "STRING",
        value: "531 NW 36TH CT",
      },
      AgentLoginID: {
        agentEditable: false,
        agentViewable: true,
        displayName: "Last Agent",
        global: false,
        isSecure: false,
        name: "AgentLoginID",
        reportable: false,
        secureKeyId: "",
        secureKeyVersion: 0,
        type: "STRING",
        value: "bmclella_agent1@email.carehybrid.com",
      },
      CAD_Open: {
        agentEditable: true,
        agentViewable: true,
        displayName: "Call Center Status",
        global: false,
        isSecure: false,
        name: "CAD_Open",
        reportable: false,
        secureKeyId: "",
        secureKeyVersion: 0,
        type: "STRING",
        value: "Open",
      },
      CaliforniaStatus: {
        agentEditable: false,
        agentViewable: true,
        displayName: "Florida Online",
        global: false,
        isSecure: false,
        name: "CaliforniaStatus",
        reportable: false,
        secureKeyId: "",
        secureKeyVersion: 0,
        type: "STRING",
        value: "online",
      },
      CallDeflected: {
        agentEditable: false,
        agentViewable: true,
        displayName: "Caller Deflected To",
        global: true,
        isSecure: false,
        name: "CallDeflected",
        reportable: true,
        secureKeyId: "",
        secureKeyVersion: 0,
        type: "STRING",
        value: "Voice",
      },
      CaseStatus: {
        agentEditable: true,
        agentViewable: true,
        displayName: "Status",
        global: false,
        isSecure: false,
        name: "CaseStatus",
        reportable: false,
        secureKeyId: "",
        secureKeyVersion: 0,
        type: "STRING",
        value: "Review",
      },
      City: {
        agentEditable: true,
        agentViewable: true,
        displayName: "City",
        global: false,
        isSecure: false,
        name: "City",
        reportable: false,
        secureKeyId: "",
        secureKeyVersion: 0,
        type: "STRING",
        value: "Cleveland",
      },
      Email: {
        agentEditable: true,
        agentViewable: true,
        displayName: "Email",
        global: false,
        isSecure: false,
        name: "Email",
        reportable: false,
        secureKeyId: "",
        secureKeyVersion: 0,
        type: "STRING",
        value: "mclellandemo@gmail.com",
      },
      "FC-DESKTOP-VIEW": {
        agentEditable: false,
        agentViewable: true,
        displayName: "",
        global: false,
        isSecure: false,
        name: "FC-DESKTOP-VIEW",
        reportable: false,
        secureKeyId: "",
        secureKeyVersion: 0,
        type: "STRING",
        value:
          '{"pop-over":[{"name":"ani","variableSeq":"0"},{"name":"dn","variableSeq":"1"},{"name":"virtualTeamName","variableSeq":"2"},{"name":"OrginalChannel","variableSeq":"3"},{"name":"AgentLoginID","variableSeq":"4"}],"interaction-panel":[{"name":"FirstName","variableSeq":"0"},{"name":"LastName","variableSeq":"1"},{"name":"Address","variableSeq":"2"},{"name":"Email","variableSeq":"3"},{"name":"City","variableSeq":"4"},{"name":"State","variableSeq":"5"},{"name":"Issue","variableSeq":"6"},{"name":"CaseStatus","variableSeq":"7"},{"name":"ani","variableSeq":"8"},{"name":"dn","variableSeq":"9"},{"name":"virtualTeamName","variableSeq":"10"},{"name":"CallDeflected","variableSeq":"11"},{"name":"Global_Language","variableSeq":"12"},{"name":"Global_FeedbackSurveyOptIn","variableSeq":"13"}]}',
      },
      FCR: {
        agentEditable: true,
        agentViewable: true,
        displayName: "FCR",
        global: true,
        isSecure: false,
        name: "FCR",
        reportable: true,
        secureKeyId: "",
        secureKeyVersion: 0,
        type: "BOOLEAN",
        value: "false",
      },
      FirstName: {
        agentEditable: true,
        agentViewable: true,
        displayName: "First Name",
        global: false,
        isSecure: false,
        name: "FirstName",
        reportable: false,
        secureKeyId: "",
        secureKeyVersion: 0,
        type: "STRING",
        value: "Barry",
      },
      Global_FeedbackSurveyOptIn: {
        agentEditable: true,
        agentViewable: true,
        displayName: "Post Call Survey Opt-in",
        global: true,
        isSecure: false,
        name: "Global_FeedbackSurveyOptIn",
        reportable: true,
        secureKeyId: "",
        secureKeyVersion: 0,
        type: "STRING",
        value: "uninitialized",
      },
      Global_Language: {
        agentEditable: false,
        agentViewable: true,
        displayName: "Customer Language",
        global: true,
        isSecure: false,
        name: "Global_Language",
        reportable: true,
        secureKeyId: "",
        secureKeyVersion: 0,
        type: "STRING",
        value: "en-US",
      },
      Issue: {
        agentEditable: false,
        agentViewable: true,
        displayName: "Issue",
        global: false,
        isSecure: false,
        name: "Issue",
        reportable: false,
        secureKeyId: "",
        secureKeyVersion: 0,
        type: "STRING",
        value: "AbsentNotify",
      },
      LastName: {
        agentEditable: true,
        agentViewable: true,
        displayName: "Last Name",
        global: false,
        isSecure: false,
        name: "LastName",
        reportable: false,
        secureKeyId: "",
        secureKeyVersion: 0,
        type: "STRING",
        value: "McLellan",
      },
      MichiganStatus: {
        agentEditable: false,
        agentViewable: true,
        displayName: "Michigan Online",
        global: false,
        isSecure: false,
        name: "MichiganStatus",
        reportable: false,
        secureKeyId: "",
        secureKeyVersion: 0,
        type: "STRING",
        value: "online",
      },
      Name: {
        agentEditable: false,
        agentViewable: true,
        displayName: "Name",
        global: false,
        isSecure: false,
        name: "Name",
        reportable: false,
        secureKeyId: "",
        secureKeyVersion: 0,
        type: "STRING",
        value: "",
      },
      OrginalChannel: {
        agentEditable: false,
        agentViewable: true,
        displayName: "Escalation From Channel",
        global: false,
        isSecure: false,
        name: "OrginalChannel",
        reportable: false,
        secureKeyId: "",
        secureKeyVersion: 0,
        type: "STRING",
        value: "",
      },
      State: {
        agentEditable: true,
        agentViewable: true,
        displayName: "State",
        global: false,
        isSecure: false,
        name: "State",
        reportable: false,
        secureKeyId: "",
        secureKeyVersion: 0,
        type: "STRING",
        value: "Ohio",
      },
      ani: {
        agentEditable: false,
        agentViewable: true,
        displayName: "ani",
        global: false,
        isSecure: false,
        name: "ani",
        reportable: false,
        secureKeyId: "",
        secureKeyVersion: 0,
        type: "STRING",
        value: "+18505598991",
      },
      dateDate: {
        agentEditable: true,
        agentViewable: true,
        displayName: "Current Date",
        global: false,
        isSecure: false,
        name: "dateDate",
        reportable: false,
        secureKeyId: "",
        secureKeyVersion: 0,
        type: "STRING",
        value: "YYYYMMDD",
      },
      dateDateTime: {
        agentEditable: true,
        agentViewable: true,
        displayName: "DateTime",
        global: false,
        isSecure: false,
        name: "dateDateTime",
        reportable: false,
        secureKeyId: "",
        secureKeyVersion: 0,
        type: "STRING",
        value: "2021-06-09T08:53",
      },
      dateDayOfTheWeek: {
        agentEditable: true,
        agentViewable: true,
        displayName: "Day Of The Week",
        global: false,
        isSecure: false,
        name: "dateDayOfTheWeek",
        reportable: false,
        secureKeyId: "",
        secureKeyVersion: 0,
        type: "STRING",
        value: " ",
      },
      dn: {
        agentEditable: false,
        agentViewable: true,
        displayName: "dn",
        global: false,
        isSecure: false,
        name: "dn",
        reportable: false,
        secureKeyId: "",
        secureKeyVersion: 0,
        type: "STRING",
        value: "+15165179312",
      },
      ronaTimeout: {
        agentEditable: false,
        agentViewable: true,
        displayName: "ronaTimeout",
        global: false,
        isSecure: false,
        name: "ronaTimeout",
        reportable: false,
        secureKeyId: "",
        secureKeyVersion: 0,
        type: "STRING",
        value: "22",
      },
      sLat: {
        agentEditable: false,
        agentViewable: true,
        displayName: "lat",
        global: false,
        isSecure: false,
        name: "sLat",
        reportable: false,
        secureKeyId: "",
        secureKeyVersion: 0,
        type: "STRING",
        value: "30.418668888889",
      },
      sLong: {
        agentEditable: false,
        agentViewable: true,
        displayName: "long",
        global: false,
        isSecure: false,
        name: "sLong",
        reportable: false,
        secureKeyId: "",
        secureKeyVersion: 0,
        type: "STRING",
        value: "-86.61346",
      },
      timeHours: {
        agentEditable: true,
        agentViewable: true,
        displayName: "timeHours",
        global: false,
        isSecure: false,
        name: "timeHours",
        reportable: false,
        secureKeyId: "",
        secureKeyVersion: 0,
        type: "INTEGER",
        value: "0",
      },
      timeTime: {
        agentEditable: true,
        agentViewable: true,
        displayName: "Time",
        global: false,
        isSecure: false,
        name: "timeTime",
        reportable: false,
        secureKeyId: "",
        secureKeyVersion: 0,
        type: "STRING",
        value: " ",
      },
      virtualTeamName: {
        agentEditable: false,
        agentViewable: true,
        displayName: "virtualTeamName",
        global: false,
        isSecure: false,
        name: "virtualTeamName",
        reportable: false,
        secureKeyId: "",
        secureKeyVersion: 0,
        type: "STRING",
        value: "bmclella_voice_Q",
      },
    },
    hasCustomerLeft: false,
    isConvNotFound: false,
    isOwner: true,
    EpDnConsultDestinationAgentJoined: false,
    isSecondaryEpDnAgent: false,
    monitoringStartTime: 1682712932773,
    type: "AgentContactAssigned",
    isMonitoringOnHold: false,
    monitoringHoldTimer: 1682712932252,
  };
};
